# Generated by Django 4.2.1 on 2023-05-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='ShopApp.image'),
        ),
    ]
