# Generated by Django 4.2.1 on 2023-05-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0010_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Stefan Mileski', max_length=200),
        ),
    ]
