# Generated by Django 4.2.1 on 2023-05-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0015_alter_review_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer', 'product')},
        ),
    ]
