# Generated by Django 4.2.1 on 2023-05-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0021_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='uploaded/default.png', upload_to='uploaded/'),
        ),
    ]
