# Generated by Django 4.2.1 on 2023-05-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0028_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_cart', to='ShopApp.cart'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='ShopApp.order'),
        ),
    ]
