# Generated by Django 4.2.1 on 2023-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0030_alter_customuser_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('seller', 'slug')},
        ),
    ]
